=== lbrayat/esb-benchmark-tool/LauncherWebApplication/build/web/WEB-INF/classes/launcherproject/xml/scenario.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="scenario">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="configuration"/>
                <xs:element ref="consumers"/>
                <xs:element ref="providers"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="actor" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

     <xs:element name="consumers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="consumer" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

     <xs:element name="providers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="provider" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="actor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="consumer"/>
                            <xs:enumeration value="provider"/>
                        </xs:restriction>
                    </xs:simpleType>
                    </xs:element>
                <xs:element name="address" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="identifier" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="consumer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="phaseConsumer" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="identifier" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="phaseConsumer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="providerId" type="xs:string"/>
		<xs:element name="targetedProviderConf" type="xs:int"/>
                <xs:element name="trafficClass">
		    <xs:simpleType>
		        <xs:restriction base="xs:string">
			    <xs:enumeration value="BE"/>
			    <xs:enumeration value="RT"/>		
		        </xs:restriction>
		    </xs:simpleType>
		</xs:element>
                <xs:element name="numberOfRequests" type="xs:positiveInteger"/>
                <xs:element name="sendPeriod" type="xs:positiveInteger"/>
                <xs:element name="packetSize" type="xs:positiveInteger"/>
                <xs:element name="startDate" type="xs:long"/>
                <xs:element name="numberOfBursts" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="provider">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="phaseProvider" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="identifier" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="phaseProvider">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="processingTime" type="xs:positiveInteger"/>
                <xs:element name="packetSize" type="xs:positiveInteger"/>
                <xs:element name="percentageLoss" type="xs:int"/>
            </xs:sequence>
	    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== lbrayat/esb-benchmark-tool/scenarioPuree2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : insa.xml
    Created on : 9 décembre 2013, 12:46
    Author     : admin
    Description:
        Purpose of the document follows.
-->
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scenario.xsd">
    <configuration>
        <actor identifier="1">
            <type>consumer</type>
            <address>http://localhost:9080/CompositeApplication/consumerPort?wsdl</address>
        </actor>
        <actor identifier="51">
            <type>provider</type>
            <address>http://localhost:9080/CompositeApplication/providerPort?wsdl</address>
        </actor>
    </configuration>
    <consumers>
        <consumer identifier="1">
                <phaseConsumer>
                    <providerId>51</providerId>
		    <targetedProviderConf>2</targetedProviderConf>
                    <trafficClass>BE</trafficClass>
                    <numberOfRequests>250</numberOfRequests>
                    <sendPeriod>10</sendPeriod>
                    <packetSize>2</packetSize>
                    <startDate>10</startDate>
                    <numberOfBursts>1</numberOfBursts>
                </phaseConsumer>
                <phaseConsumer>
                    <providerId>51</providerId>
		    <targetedProviderConf>1</targetedProviderConf>
                    <trafficClass>RT</trafficClass>
                    <numberOfRequests>2000</numberOfRequests>
                    <sendPeriod>10</sendPeriod>
                    <packetSize>3</packetSize>
                    <startDate>30</startDate>
                    <numberOfBursts>1</numberOfBursts>
                </phaseConsumer>
        </consumer>
    </consumers>
    <providers>
        <provider identifier="51">
            <phaseProvider id="1">
                <processingTime>60</processingTime>
                <packetSize>5</packetSize>
                <percentageLoss>0</percentageLoss>
            </phaseProvider> 
            <phaseProvider id="2">
                <processingTime>2</processingTime>
                <packetSize>10</packetSize>
                <percentageLoss>0</percentageLoss>
            </phaseProvider>
        </provider>
    </providers>
</scenario>

=== lbrayat/esb-benchmark-tool/LauncherProject/test/scenario.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : insa.xml
    Created on : 9 dÃ©cembre 2013, 12:46
    Author     : admin
    Description:
        Purpose of the document follows.
-->

<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scenario.xsd">
    <configuration>
        <actor identifier="1">
            <type>consumer</type>
            <address>http://localhost:8080/ConsumerProject/ConsumerWebServiceService?wsdl</address>
        </actor>
        <actor identifier="2">
            <type>consumer</type>
            <address>192.168.1.3</address>
        </actor>
        <actor identifier="3">
            <type>consumer</type>
            <address>192.168.1.4</address>
        </actor>
        <actor identifier="51">
            <type>provider</type>
            <address>192.168.1.5</address>
        </actor>
        <actor identifier="52">
            <type>provider</type>
            <address>192.168.1.6</address>
        </actor>
    </configuration>
    <consumers>
        <consumer identifier="1">
                <phaseConsumer>
                    <providerId>51</providerId>
                    <trafficClass>BE</trafficClass>
                    <numberOfRequests>3000</numberOfRequests>
                    <sendPeriod>1</sendPeriod>
                    <packetSize>1024</packetSize>
                    <startDate>0</startDate>
                    <numberOfBursts>1000</numberOfBursts>
                </phaseConsumer>
                <phaseConsumer>
                    <providerId>51</providerId>
                    <trafficClass>RT</trafficClass>
                    <numberOfRequests>5000</numberOfRequests>
                    <sendPeriod>1</sendPeriod>
                    <packetSize>1024</packetSize>
                    <startDate>1000</startDate>
                    <numberOfBursts>2000</numberOfBursts>
                </phaseConsumer>
        </consumer>
        <!--
        <consumer identifier="2">

                <phaseConsumer>
                    <providerId>52</providerId>
                    <trafficClass>RT</trafficClass>
                    <numberOfRequests>9000</numberOfRequests>
                    <sendPeriod>2</sendPeriod>
                    <packetSize>1024</packetSize>
                    <startDate>0</startDate>
                    <numberOfBursts>3000</numberOfBursts>
                </phaseConsumer>

        </consumer>
        <consumer identifier="3">
                <phaseConsumer>
                    <providerId>52</providerId>
                    <trafficClass>RT</trafficClass>
                    <numberOfRequests>5000</numberOfRequests>
                    <sendPeriod>3</sendPeriod>
                    <packetSize>2048</packetSize>
                    <startDate>0</startDate>
                    <numberOfBursts>1000</numberOfBursts>
                </phaseConsumer>
                <phaseConsumer>
                    <providerId>52</providerId>
                    <trafficClass>RT</trafficClass>
                    <numberOfRequests>5000</numberOfRequests>
                    <sendPeriod>2</sendPeriod>
                    <packetSize>2048</packetSize>
                    <startDate>1000</startDate>
                    <numberOfBursts>500</numberOfBursts>
                </phaseConsumer>
                <phaseConsumer>
                    <providerId>51</providerId>
                    <trafficClass>RT</trafficClass>
                    <numberOfRequests>5000</numberOfRequests>
                    <sendPeriod>50</sendPeriod>
                    <packetSize>4096</packetSize>
                    <startDate>2000</startDate>
                    <numberOfBursts>20</numberOfBursts>
                </phaseConsumer>
        </consumer>
-->
    </consumers>
    <providers>
        <provider identifier="51">
            <phaseProvider>
                <processingTime>0.001</processingTime>
                <numberOfResponses>112</numberOfResponses>
                <packetSize>1024</packetSize>
                <percentageLoss>0.01</percentageLoss>
                <startDate>0</startDate>
                <endDate>500</endDate>
            </phaseProvider>
            <phaseProvider>
                <processingTime>0.00003</processingTime>
                <numberOfResponses>76</numberOfResponses>
                <packetSize>2048</packetSize>
                <percentageLoss>0.05</percentageLoss>
                <startDate>500</startDate>
                <endDate>2500</endDate>
            </phaseProvider>
            <phaseProvider>
                <processingTime>0.01</processingTime>
                <numberOfResponses>50</numberOfResponses>
                <packetSize>1024</packetSize>
                <percentageLoss>0.02</percentageLoss>
                <startDate>2500</startDate>
                <endDate>3000</endDate>
            </phaseProvider>
        </provider>
        <provider identifier="52">
            <phaseProvider>
                <processingTime>0.01</processingTime>
                <numberOfResponses>22</numberOfResponses>
                <packetSize>1024</packetSize>
                <percentageLoss>0.02</percentageLoss>
                <startDate>0</startDate>
                <endDate>3000</endDate>
            </phaseProvider>
        </provider>
    </providers>
</scenario>
